apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue-deployment
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
      version: blue
  template:
    metadata:
      labels:
        app: django
        version: blue
    spec:
      containers:
      - name: django-container
        image: ahmed2013/django-app:v1.0
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_DATABASE
          value: "django_db_user"
        - name: MYSQL_USER
          value: "none"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "3306"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000 #used outside by another services
      targetPort: 8000 #inside pod
  type: ClusterIP