apiVersion: v1
kind: Service
metadata:
  name: django-green-service
spec:
  selector:
    app: django
    version: green
  ports:
    - protocol: TCP
      port: 8000 #used outside by another services
      targetPort: 8000 #inside pod
  type: ClusterIP