pipeline {
	agent any
	environment{
		GITHUB_CREDENTIALS_ID = 'github-credentials'
		DOCKERHUB_CREDENTIALS_ID = 'dockerhub-credentials'
		VENV_DIR = '.venv'
		REPO_URL = 'https://github.com/ahmed2103/alx-backend-python'
		APP_DIR = 'alx-backend-python/messaging_app'
		IMAGE_NAME = 'messaging_app'
		IMAGE_TAG = 'latest'
	}
	stages {
		stage("Checkout") {
			steps {
				echo "Checking out source code..."
				git branch: 'main'
				credentialsId: "${env.GITHUB_CREDENTIALS_ID}"
				url: ${env.REPO_URL}
			}
		}
		stage{
			steps {
					echo "Setting up Python virtual environment..."
					sh """
						python3 -m venv ${env.VENV_DIR}
						source ${env.VENV_DIR}/bin/activate
						pip3 install --upgrade pip
						pip3 install -r messaging_app/requirements.txt
					"""
			}
		}
		stage("Run Tests") {
			steps {
				dir("${env.APP_DIR}") {
					echo "Running unit tests..."
					sh """
						source ${env.VENV_DIR}/bin/activate
						mkdir -p test_reports
						pytest tests/ --junitxml=test_reports/results.xml
					"""
				}
			}
		}
		stage("Archive Test Results") {
			steps {
				dir("${env.APP_DIR}") {
					echo "Archiving test results..."
					junit 'test_reports/results.xml'
				}
			}
		}
		stage("Build Docker Image") {
			steps {
				dir("${env.APP_DIR}") {
					echo "Building Docker image..."
					sh """
						docker build -t ${env.IMAGE_NAME}:${env.IMAGE_TAG} .
					"""
				}
			}
		}
		stage("Push Docker Image") {
			steps {
				echo "Pushing Docker image to Docker Hub..."
				withCredentials([usernamePassword(credentialsId: "${env.DOCKERHUB_CREDENTIALS_ID}", passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
					sh """
						docker tag ${env.IMAGE_NAME}:${env.IMAGE_TAG} $DOCKERHUB_USERNAME/${env.IMAGE_NAME}:${env.IMAGE_TAG}
						docker push $DOCKERHUB_USERNAME/${env.IMAGE_NAME}:${env.IMAGE_TAG}
					"""
				}
			}
		}
	}
	post {
		always {
			echo "Cleaning up virtual environment..."
			sh "rm -rf ${env.VENV_DIR}"
		}
		success {
			echo "pipeline succeeded!"
		}
		failure {
			echo "pipeline failed!"

		}
	}
}